Repository eclipse-tractusx/tutorial-resources, pull requests merged in 2024-11, with the labels that each got.

#474 feat: Adds Trufflehog workflow
  .github/workflows/secrets-scan.yml
Labels: enhancement

#485 fix(deployment): use correct catalogserver url
  mxd/README.md
  mxd/alice.tf
  mxd/assets/participants.json
Labels: bug

#486 chore: bump versions
  mxd-runtimes/e2e-test/src/test/java/org/eclipse/edc/demo/tests/transfer/TransferEndToEndTest.java
  mxd-runtimes/gradle/catalogserver.versions.toml
  mxd-runtimes/gradle/libs.versions.toml
  mxd/modules/connector/connector.tf
Labels: dependencies, java
